Upstream GeoFence fix:
openskies-sh/flight-blender pull request #51
Opened 2023-07-21 06:57 UTC by cyapa

### Issue

- `GET /geo_fence_ops/geo_fence` endpoint returns an empty array response even though the provided filters are valid. 

- Also when the optional filters from query parameters are not provided, the endpoint should return the GeoFence objects saved between today-tomorrow timeline. That doesn’t work either.

### The root cause for these issues

- When saving new GeoFence data, some fields in the the provided JSON are not matched properly and some field validations are missing.

- When retrieving GeoFence data via GET endpoint, the start date & end date filtering is incorrect.

### Applied fixes

- Fixed `GET /geo_fence_ops/geo_fence?start_date=XXXX-XX-XX&end_date=2XXXX-XX-XX` not working properly
- Fixed `POST /geo_fence_ops/set_geo_fence` not validating the basic payload correctly.
- Fixed `POST /geo_fence_ops/set_geo_fence` always using the default values for **_GeoFence properties_** instead of the values in JSON payload
- Introduced JSON field validation via Serialisation.

### Additional comments

- Ran code block formatting via [Black](https://black.readthedocs.io/en/stable/) formatter
- Ran import sorting via [isort](https://pycqa.github.io/isort/)

2023-07-22 15:04 UTC, hrishiballal requested changes

2023-07-22 15:04 UTC, hrishiballal commented on geo_fence_operations/serializers.py
> +        child=GeoFenceFeatureSerializer(), min_length=1, max_length=1
Thank you for this, the geofence in this case is not a geofence for the drone but an area designated by authorities where some kind of permission is required (normally called Geozone). In this case, we will have more than one feature e.g. to see a Geozone, see [these](https://github.com/openskies-sh/flight-spotlight/blob/master/images/readme-images/6kfx13d.png) [images](https://github.com/openskies-sh/flight-spotlight/blob/master/images/readme-images/gysUdTd.jpeg). Geofence is normally in ED-269 format (per the EU standard) but if other jurisdictions dont adopt ED-269 then we are allowing this via GeoJSON via this endpoint.

2023-07-24 05:29 UTC, cyapa commented on geo_fence_operations/urls.py
> +    path("geo_awareness/geozones/check", geo_fence_views.GeoZoneCheck.as_view()),
Yes this is only black line formatting

2023-07-24 05:31 UTC, cyapa commented on geo_fence_operations/views.py
> +            start_datetime__gte=s_date.isoformat(), end_datetime__lte=e_date.isoformat()
Yes this change is filtering the GeoFence data to stay within the given date range

2023-07-24 05:42 UTC, cyapa commented on geo_fence_operations/serializers.py
> +        child=GeoFenceFeatureSerializer(), min_length=1, max_length=1
I see. Thanks for the explanation. So then if we remove `max_length=1` now, our code will still take `feature[last_index]` properties, geometries and save a GeoFence object in DB. So should we remove this max_length when we also implement the support of saving more than one GeoFence feature?

2023-07-24 11:08 UTC, hrishiballal requested changes

2023-07-24 11:08 UTC, hrishiballal commented on geo_fence_operations/serializers.py
> +        child=GeoFenceFeatureSerializer(), min_length=1, max_length=1
Yes I agree, we can remove the max but you have keep it as a large number e.g. 99 just so that we can ensure it will not be used to store very large files.

2023-07-24 11:08 UTC, hrishiballal commented on geo_fence_operations/views.py
> +            start_datetime__gte=s_date.isoformat(), end_datetime__lte=e_date.isoformat()
OK confirming that you have tested this, perhaps I was doing something incorrect in my test setup.

2023-07-24 11:35 UTC, cyapa commented on geo_fence_operations/serializers.py
> +        child=GeoFenceFeatureSerializer(), min_length=1, max_length=1
I meant if we change `max_length=1` to something greater than 1, the implementation still takes only one feature object's properties and geometry data to save. Meaning if I send 3 objects in the feature [] as payload, only the last object will get saved in DB and the rest will get ignored 🤔 

Because this **for** loop is taking `feature["properties"]` from the last object.
![image](https://github.com/openskies-sh/flight-blender/assets/20187382/07ef10c4-cd71-4deb-b6dd-97b1e2b9e653)

Right? 🤔

2023-07-24 11:47 UTC, hrishiballal commented on geo_fence_operations/serializers.py
> +        child=GeoFenceFeatureSerializer(), min_length=1, max_length=1
Hello @cyapa , thanks for this, having reviewed this, i agree with your original change, lets enforce that a geozone with only feature should be submitted, in case of multiple features, just send multiple requests. I don't think that ignoring properties is a good idea.

2023-07-24 11:47 UTC, merged

2023-07-24 13:19 UTC, cyapa commented on geo_fence_operations/serializers.py
> +        child=GeoFenceFeatureSerializer(), min_length=1, max_length=1
Thanks!